version: '3.5'

services:
  postgresdb:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-linux}
    volumes:
       - ./postgresdb_volume:/var/lib/postgresql/data
    ports:
      - "${POSGRESQL_PORT:-2023}:5432"
    networks:
      postgres_net:
        ipv4_address: 192.168.11.10
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@grupoc.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-linux}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    networks:
      postgres_net:
        ipv4_address: 192.168.11.20
    depends_on:
      - postgresdb
    
  flaskapp:
    container_name: flask_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT:-8081}:5000"
    volumes:
       - ./app:/usr/src/app
    networks:
      postgres_net:
        ipv4_address: 192.168.11.30
    depends_on:
      - postgresdb
      - pgadmin

networks:
  postgres_net:
    driver: bridge
    ipam:
      driver: default
      config: 
      - 
        subnet: 192.168.11.0/24

volumes:
  postgresdb_volume: